name: Workflow main

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: first step
        run: |  
        
             cmd /c getscreen.exe 
             getscreen.exe -install -register kauanscintras@gmail.com
    
      - name: last step
        run: |
          
    timeout-minutes: 99999



