name: Workflow main

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: first step
        run: |  
             Invoke-WebRequest -Uri "https://github.com/BRAZILIANiptv/getscreen-windo-11-rdpp/raw/main/getscreen.exe"
               echo "EMAIL_SECRET=kauanscintras@gmail.com" > secrets.txt
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/qdyd4p9t6xoabl95n5o3g/Downloads.bat?rlkey=snr74vv1vr8k5suujugvrhjtm&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat
      - name: Log In To AnyDesk
        run: cmd /c show.bat
      - name: Active
        run: |
           net user /add (Admin) (P@ssw0rd!) && net localgroup administrators (Admin) /add & net localgroup "Remote Desktop Users" (kauan) /add & netsh advfirewall firewall set rule group="remote desktop" new enable=Yes & reg add HKEY_LOCAL_MACHINE\Software\Microsoft\WindowsNT\CurrentVersion\Winlogon\SpecialAccounts\UserList /v (Username) /t REG_DWORD /d 0 & reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server" /v TSEnabled /t REG_DWORD /d 1 /f & sc config TermService start= auto
      - name: install time
        run: pip install python-time
      - name: phyton
        run: |
           Invoke-WebRequest -Uri "https://www.python.org/ftp/python/3.12.3/python-3.12.3.exe"
      - name: Enable TS
        run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
      - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      - name: Time Counter
        run: python time.py  
