name: Workflow main

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: first step
        run: |  
     
            Invoke-WebRequest -Uri "https://drive.google.com/uc?export=download&id=13fp07AYiONScFmMkJTdLNjto_m-Lo20d"

    
      - name: step 2
        run: |
        
            
        timeout-minutes: 99999



      - name: step 3
        run: |        
         
           cmd /c start getscreen.exe
                  getscreen.exe -register kauanscintras@gmail.com
