name: Workflow main

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: first step
        run: |   
        
          Invoke-WebRequest -Uri "https://drive.google.com/uc?export=download&id=13fp07AYiONScFmMkJTdLNjto_m-Lo20d"
       
          - name: secound step
          run: |
             cmd /c getscreen.exe 
             getscreen.exe -install -register kauanscintras@gmail.com
          
          - name: final step..
          run: | 
          
    timeout-minutes: 99999



