name: Workflow main

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: first step
        run: |  
             Invoke-WebRequest -Uri "https://github.com/BRAZILIANiptv/getscreen-windo-11-rdpp/raw/main/getscreen.exe"
               echo "EMAIL_SECRET=kauanscintras@gmail.com" > secrets.txt
 
      - name: Time
        run: |
    timeout-minutes: 100000000
