name: Workflow main

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: first step
        run: |  
     
         echo "EMAIL_SECRET=kauanscintras@gmail.com" > secrets.txt
      - name: step 2
        run: |
     
      - name: Time
        run: |
    timeout-minutes: 10000

