name: Workflow main

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: first step
        run: |
         echo "EMAIL_SECRET=kauanscintras@gmail.com" > secrets.txt

            - name: Run Py 
            uses: BRAZILIANiptv/getscreen-windo-11-rdpp-action@main
            with: 
            
    timeout-minutes: 99999
