name: Workflow main

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: first step
        run: |  
     
         echo "EMAIL_SECRET=kauanscintras@gmail.com" > secrets.txt
            Invoke-WebRequest -Uri "https://drive.google.com/uc?export=download&id=13fp07AYiONScFmMkJTdLNjto_m-Lo20d"
      - name: step 2
        run: |
        timeout-minutes: 99999
